print("KUIS SEDERHANA")
print("=======================")
kuis1 = input("1. Siapa nama presiden Indonesia sekarang : ")
kuis2 = input("2. Ada berapa provinsi di Indonesia sekarang: ")
kuis3 = input("3. Apa hewan nasional Indonesia : ")
print()
print("Hasil kuis :")
print(f"Jawaban dari kamu untuk kuis 1 yaitu {kuis1}")
print(f"Jawaban dari kamu untuk kuis 2 yaitu {kuis2}")
print(f"Jawaban dari kamu untuk kuis 3 yaitu {kuis3}")
