print("SURAT LAMARAN DIGITAL")
print("========================")
print("Isi pertanyaan berikut :")
nama = input("Masukan nama : ")
posisi = input("Posisi yang ingin dilamar : ")
perusahaan = input("Nama perusahaan yang dilamar : ")
keahlian = input("Masukan keahlian utama : ")
print()
print("Membuat surat lamaran :")
print()
print("Surat Lamaran Bekerja")
print(f"Yth. HRD {perusahaan}")
print("Saya ingin melamar pekerjaan di perusahaan anda, ini adalah surat lamaran dari saya :")
print(f"Nama : {nama}")
print(f"Posisi yang dilamar : {posisi}")
print(f"Keahlian utama : {keahlian}")
print("Sekian dari saya, salam sejahtera")
